import type { Entry } from './domain';
const base = { author: 'Muse Community', protocol: 'Prompt', endpoint: '', docsUrl: '', auth: 'None', permissions: '', privacyUrl: '', termsUrl: '', supportUrl: '', status: 'published', createdAt: '2026-09-21T00:00:00.000Z', votes: 0, comments: 0, saved: false, voted: false, owned: false, source: 'Starter guide' };
export const starterEntries: Entry[] = [
    { id: 'weekly-reset', kind: 'workflow', title: 'A calmer start to the week', description: 'Turn a busy calendar and a loose to-do list into a realistic plan, with room to breathe.', category: 'Everyday life', body: 'Help me plan the next seven days. Ask for my commitments, top three priorities, working hours, and anything I want to protect time for. Propose a realistic plan with buffers. Explain conflicts. Do not change my calendar or message anyone until I approve the exact changes. If you cannot access my calendar, ask me to paste the relevant events.' },
    { id: 'trip-brief', kind: 'workflow', title: 'Plan the trip before booking a thing', description: 'A reusable brief for comparing travel options against a real budget and a few personal preferences.', category: 'Travel', body: 'Help me plan a trip. Ask for dates, departure city, destination preferences, group size, accessibility needs, and total budget. Compare three options with sources, date checked, estimated total cost, and cancellation terms. Mark prices that are not live. Do not book, pay, or submit personal details without my approval.' },
    { id: 'meeting-brief', kind: 'workflow', title: 'Walk into your next meeting prepared', description: 'Bring the background, open questions, and decisions together in one useful brief.', category: 'Work', body: 'Prepare a meeting brief using only the notes and documents I authorize. Include participants, objective, relevant context, unresolved questions, and decisions needed. Link every factual claim to its source where available. List missing context. Do not send the brief to anyone.' },
    { id: 'subscription-review', kind: 'workflow', title: 'Find the subscriptions you still want', description: 'Make a clear keep, review, or cancel list from the information you choose to share.', category: 'Money', body: 'Help me review recurring subscriptions from the redacted statement or list I provide. Group the charges, flag price changes and possible duplicates, and calculate monthly and yearly totals. Do not assume a duplicate is an error. Ask about usage before suggesting cancellations. Do not cancel services or contact providers.' },
    { id: 'learn-by-doing', kind: 'workflow', title: 'Learn something by making something', description: 'Build a small personal project around a topic you have been meaning to understand.', category: 'Learning', body: 'Ask what I want to learn, what I already know, and how much time I can spend this week. Propose a small project that teaches the essentials. Break it into sessions with a tangible result and one check of understanding each. Adjust after my feedback; do not enroll me in paid courses.' },
    { id: 'connector-brief', kind: 'workflow', title: 'Turn an app into a connector brief', description: 'Give a developer the operations, permissions, and acceptance checks that matter to your users.', category: 'Building', body: 'Help me scope a connector for my app. Ask for the official API documentation and three real user tasks. Map each task to documented endpoints, authorization scopes, read/write behavior, confirmation needs, and expected responses. Identify unsupported operations instead of inventing APIs. Produce a review checklist and an example prompt.' },
    { id: 'notion-mcp', kind: 'connector', title: 'Notion', description: 'Find workspace knowledge and work with pages through Notion’s hosted MCP server.', category: 'Work', protocol: 'MCP', endpoint: 'https://mcp.notion.com/mcp', docsUrl: 'https://developers.notion.com/guides/mcp/overview', auth: 'OAuth', permissions: 'Access is limited by your Notion permissions and the connection you authorize. Tools may read and update content.', body: 'Find the notes I authorized for my next meeting and prepare a brief. Do not change any pages.', source: 'Provider documentation', author: 'Notion' },
    { id: 'stripe-mcp', kind: 'connector', title: 'Stripe', description: 'Work with payment operations and search Stripe documentation from a compatible MCP client.', category: 'Money', protocol: 'MCP', endpoint: 'https://mcp.stripe.com', docsUrl: 'https://docs.stripe.com/mcp', auth: 'OAuth', permissions: 'Choose the account and permissions at authorization. Start in a sandbox; money-moving operations require explicit approval.', body: 'Explain my available Stripe reporting tools and help me prepare a read-only balance review.', source: 'Provider documentation', author: 'Stripe' },
    { id: 'square-api', kind: 'connector', title: 'MuseSquare Discovery', description: 'Let an agent search this connector catalog and retrieve the details it needs to evaluate a listing.', category: 'Building', protocol: 'OpenAPI', endpoint: '/api/catalog', docsUrl: '/api/openapi', auth: 'None', permissions: 'Read-only public listings. The private preview requires site access. No external accounts are connected.', body: 'Find connectors in MuseSquare that could help me organize my work. Show permissions, sources, and the Muse compatibility status.', source: 'Built in this project' },
    { id: 'town-mcp', kind: 'connector', title: 'MuseTown Experiences', description: 'Give an agent read-only access to shared workflows and requests from the community.', category: 'Building', protocol: 'MCP', endpoint: '/api/mcp', docsUrl: '/studio', auth: 'None', permissions: 'Read-only published experiences and catalog. The private preview requires site access. Cannot post, purchase, or run third-party tools.', body: 'Find a starter workflow for planning my week and show me the prompt before using it.', source: 'Built in this project' }
].map(e => ({ ...base, ...e })) as Entry[];
